project:
  type: book
  # output-dir: _book
  output-dir: docs

book:
  title: "Master's thesis in Bioinformatics and Computational Biology"
  # subtitle: "Single-cell transcriptomics analysis of mutant competition during field cancerization in mouse esophagus" 
  author: "Alba Méndez Alejandre"
  date: last-modified
  date-format: "DD/MM/YYYY"
  search: true
  repo-url: https://github.com/alba179/master-thesis-bioinfo
  sidebar:
    style: floating
    collapse-level: 2
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Mouse analysis"
      chapters:
        - Mouse/1_DataProcessing.qmd
        - Mouse/2_ClusteringCellAnnotation.qmd
        - Mouse/3_Velocity_inference.qmd
        - Mouse/4_VariantCalling.qmd
        - Mouse/5_AnnotationVariants.qmd
        - Mouse/6_GOAnalysis.qmd
    - part: "Human HCA analysis"
      chapters:
        # - Human/1_hca_esoph_inspection.qmd
        # - Human/2_GeneExpression_hca.qmd
        - Human/3_VennDiagrams_hca.qmd
        # - Human/4_clones_UMAP_mappging_hca.qmd
        # - Human/mut_clones_analysis_hca.qmd

execute: 
  enabled: false
  eval: false

format:
  html:
    theme: cosmo
    number-sections: false       
    code-fold: false               
    toc: true                    
    toc-depth: 5
    toc-expand: 4
    toc-location: right
    toc-title: "Index"
  pdf:
    toc: true
    documentclass: scrreprt