project:
  type: book
  # output-dir: _book
  output-dir: docs

book:
  title: "Master thesis in Bioinformatics and Computational Biology"
  subtitle: "Single-cell transcriptomics analysis of mutant competition during field cancerization in mouse esophagus" 
  author: "Alba Méndez Alejandre"
  date: last-modified
  date-format: "DD/MM/YYYY"
  search: false
  repo-url: https://github.com/alba179/master-thesis-bioinfo
  sidebar:
    style: floating
    collapse-level: 1
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Mouse analysis"
      chapters:
        - Mouse/1_DataProcessing.qmd
        - Mouse/2_ClusteringCellAnnotation.qmd
        - Mouse/3_Velocity_inference.qmd
        # - Mouse/4_SComatic_VariantCalling.qmd
        - Mouse/5_AnnotationVariants.qmd
        - Mouse/6_FunctionalAnalysis.qmd
    - part: "Human HCA analysis"
      chapters:
        - Human/
        - Human/

execute: 
  enabled: false
  eval: false

format:
  html:
    theme: cosmo
    number-sections: false       
    code-fold: true              
    toc: true                    
    toc-depth: 5
    toc-expand: 3
    toc-location: right
    toc-title: "Index"
  pdf:
    toc: true
    documentclass: scrreprt